### ISSUE TITLE
obmc-rest did not activate

### ISSUE THREAD

**Issue by Kenthliu** [openbmc/phosphor-rest-server#23]
I had tested in 2 system. 
One system happened randomly. The system is connected LAN to my laptop directly.
I found there is no obmc-rest procedure sometimes.
Attachment is the journalctl log that is no obmc-rest situation.
[norest1.txt](https://github.com/openbmc/phosphor-rest-server/files/331506/norest1.txt)
This is another journalctl log that get obmc-rest
[getrest.txt](https://github.com/openbmc/phosphor-rest-server/files/331512/getrest.txt)

There is another system that always can not see the obmc-rest. 
The environment is a little different. The system BMC LAN port is connected to WAN, and the IP is assigned by DHCP.
Here is the log.
[norest2.txt](https://github.com/openbmc/phosphor-rest-server/files/331515/norest2.txt)

I think the key point is the message.
Jun 22 08:59:55 barreleye systemd[1]: Failed to start Phosphor OpenBMC DBus service management daemon.
Jun 22 08:59:55 barreleye systemd[1]: Dependency failed for Phosphor OpenBMC DBus REST daemon.
Jun 22 08:59:55 barreleye systemd[1]: obmc-rest.service: Job obmc-rest.service/start failed with result 'dependency'.

**Comment by Kenthliu** [comment]
@williamspatrick @bradbishop Please help to look into this issue. Thanks.

**Comment by bradbishop** [comment]
I was able to reproduce this by creating 128 logs.

I think I have solved it with some performance improvements here: https://github.com/openbmc/phosphor-objmgr/commit/59800b8326233b6f662a423b9e113e2b823fd744.

Also, as a safeguard, I bumped the mapper service start timeout from 90 to 300 seconds.

**Comment by Kenthliu** [comment]
This issue seems fixed in 1.0.1.  Thanks.
