### ISSUE TITLE
Enumerate on root path gives 500 return code

### ISSUE THREAD

**Issue by mkumatag** [openbmc/phosphor-rest-server#8]
[manjunath@oc1275007250 ~]$ curl -X GET https://9.3.164.147/enumerate -k
{
  "data": {
    "description": "Internal Server Error",
    "exception": "DBusException('Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.',)",
    "traceback": [
      "Traceback (most recent call last):",
      "  File \"/usr/lib/python2.7/site-packages/bottle.py\", line 862, in _handle",
      "    return route.call(*_args)",
      "  File \"/usr/lib/python2.7/site-packages/bottle.py\", line 1734, in wrapper",
      "    rv = callback(_a, *_ka)",
      "  File \"/usr/sbin/obmc-rest\", line 471, in wrap",
      "    resp = { 'data': callback(_a, **kw) }",
      "  File \"/usr/sbin/obmc-rest\", line 51, in __call__",
      "    return getattr(self, 'do_' + request.method.lower())(*_kw)",
      "  File \"/usr/sbin/obmc-rest\", line 167, in do_get",
      "    objs[x] = self.app.instance_handler.do_get(x)",
      "  File \"/usr/sbin/obmc-rest\", line 338, in do_get",
      "    path, *item))",
      "  File \"/usr/sbin/obmc-rest\", line 357, in get_properties_on_bus",
      "    properties_iface, i))",
      "  File \"/usr/sbin/obmc-rest\", line 345, in get_properties_on_iface",
      "    properties_iface.GetAll, iface)",
      "  File \"/usr/sbin/obmc-rest\", line 73, in try_properties_interface",
      "    return f(_a)",
      "  File \"/usr/lib/python2.7/site-packages/dbus/proxies.py\", line 145, in **call**",
      "    **keywords)",
      "  File \"/usr/lib/python2.7/site-packages/dbus/connection.py\", line 651, in call_blocking",
      "    message, timeout)",
      "DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."
    ]
  },
  "message": "500 Internal Server Error",
  "status": "error"
}[manjunath@oc1275007250 ~]$

above call hangs for ~20 odd sec and then throws this error.

version:

root@palmetto:~# cat /etc/_release_
ID=openbmc-phosphor
NAME=Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro)
VERSION=0.1.0 (master)
VERSION_ID=v0.1
PRETTY_NAME=Phosphor OpenBMC (Phosphor OpenBMC Project Reference Distro) 0.1.0 (master)
BUILD_ID=v0.1-48-g55c7ac3-dirty
root@palmetto:~#

**Comment by bradbishop** [comment]
This has been working OK for me lately.  Can it be closed?
